### ISSUE TITLE
Doesn't work on unix?

### ISSUE THREAD

**Issue by navaru** [OhMeadhbh/node-mug#9]
Doesn't compile on Lion OS, I get this compile error:

Waf: Entering directory `/Volumes/Lab/Apps/hass/app/node_modules/node-mug/build'
[1/2] cxx: src/mug.cc -> build/Release/src/mug_1.o
../src/mug.cc: In function ‘v8::Handle<v8::Value> mug::MACAddress(const v8::Arguments&)’:
../src/mug.cc:41: error: ‘SIOCGIFHWADDR’ was not declared in this scope
../src/mug.cc:47: error: ‘struct ifreq’ has no member named ‘ifr_hwaddr’
Waf: Leaving directory`/Volumes/Lab/Apps/hass/app/node_modules/node-mug/build'
Build failed:  -> task failed (err #1): 
    {task: cxx mug.cc -> mug_1.o}

**Comment by OhMeadhbh** [comment]
nope. works fine on unix. but it looks like it has a problem with mach. looks like our friends at apple don't implement the unix' SIOCGIFHWADDR ioctl. looks like i have to use apple's IOKit to get the same functionality.

looks like the fix is pretty straight-forward, but i don't have apple hardware to test on, so... i'll build a feature branch and ask you to test it. and if / when it works, i'll merge it into the main branch.

**Comment by navaru** [comment]
Sure, I'll be glad to help
